<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Kuria\\Console\\' => array($vendorDir . '/kuria/console/src'),
);
