<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    $vendorDir . '/gettext/gettext/Gettext/translator_functions.php',
    $vendorDir . '/php-activerecord/php-activerecord/ActiveRecord.php',
);
