<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Whoops' => array($vendorDir . '/filp/whoops/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Requests' => array($vendorDir . '/rmccue/requests/library'),
    'PHPImageWorkshop' => array($vendorDir . '/sybio/image-workshop/src'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'Gettext' => array($vendorDir . '/gettext/gettext'),
);
